version: "3.8"

services:
  scala-backend:
    build: ./scala-backend
    ports:
      - "9000:9000"
    volumes:
      - ./scala-backend:/app:cached
    depends_on:
      - db
    profiles:
      - scala
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
    restart: always

  nodejs-backend:
    build: ./nodejs-backend
    ports:
      - "9000:9000"
    depends_on:
      - db
    profiles:
      - nodejs
    volumes:
      - ./nodejs-backend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=parent_profile

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parent_profile
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  flyway:
    image: flyway/flyway:8.0.0
    command: -url=jdbc:mysql://db:3306/parent_profile -user=root -password=root -locations=filesystem:/migrations migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    restart: "on-failure"
volumes:
  db_data:
